name: PyTest
on: pull_request
jobs:
  pytest:
    name: Run application's test with PyTest
    runs-on: ubuntu-20.04
    container: fedora:34
    steps:
    - name: Install Pipenv and Git
      run: dnf install -y pipenv git
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Steup environment
      run: pipenv sync --dev
    - name: Create migrations
      run: pipenv run python manage.py makemigrations
    - name: Migrate
      run: pipenv run python manage.py migrate
    - name: Run PyTest
      run: pipenv run pytest -v
